# Generated by Django 4.2.7 on 2023-11-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('beds', models.IntegerField()),
                ('booked', models.BooleanField(default=False)),
            ],
        ),
    ]
