# Generated by Django 4.2.7 on 2023-11-30 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 6, 40, 48, 719617)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.PositiveIntegerField(),
        ),
    ]
