# Generated by Django 4.2.7 on 2023-12-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_room_available_from_alter_room_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.PositiveIntegerField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
